# Vagrant/Ansible Project
# Tzvetan Tzvetkov <tzvetan.tzvetkov@upnetix.com>

- hosts: webservers
  become: true
  remote_user: "{{ remote_user }}"

  pre_tasks:
    - debug:
        msg: "Run on server: {{ ansible_host }}"
    - name: Load vars
      include_tasks: tasks/load-vars.yml

  roles:
    - app_setup
    - upnetix.db_migrations