<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="view/css/welcomePage.css">
    <link rel="stylesheet" href="css/main.css">
    <script
            src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
    <title>Finance Tracker</title>
</head>

<body data-spy="scroll" data-target="#main-nav" id="home">
<!-- HERE WE GO -->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top" id="main-nav">
    <div class="container">
        <a href="../../index.php" class="navbar-brand">
            <img src="view/uploads/logo-wallet.png"  width="60" alt="">
            Finance Tracker
        </a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="#home-section" class="nav-link">Home</a>
                </li>
                <li class="nav-item">
                    <a href="#explore-head-section" class="nav-link">What is Finance Tracker?</a>
                </li>
                <li class="nav-item">
                    <a href="#create-head-section" class="nav-link">Start Now</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- HOME SECTION -->
<header id="home-section">
    <div class="dark-overlay">
        <div class="home-inner container">
            <div class="row">
                <div class="col lg-8 d-none d-lg-block">
                    <h1 class="display-4">Finance Tracker</h1>
                    <div class="d-flex">
                        <div class="p-4 align-self-start">
                            <i class="fas fa-check fa-2x"></i>
                        </div>
                        <div class="p-4 align-self-end">
                            <h3>Be organized</h3>
                        </div>
                    </div>
                    <div class="d-flex">
                        <div class="p-4 align-self-start">
                            <i class="fas fa-check fa-2x"></i>
                        </div>
                        <div class="p-4 align-self-end">
                            <h3>Be a team player</h3>
                        </div>
                    </div>
                    <div class="d-flex">
                        <div class="p-4 align-self-start">
                            <i class="fas fa-check fa-2x"></i>
                        </div>
                        <div class="p-4 align-self-end">
                            <h3>Be in control</h3>
                        </div>
                    </div>
                    <div class="d-flex">
                        <div class="p-4 align-self-start">
                            <i class="fas fa-check fa-2x"></i>
                        </div>
                        <div class="p-4 align-self-end">
                            <h3>Be in prepared</h3>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="card bg-primary text-center card-form">
                        <div class="card-body">
                            <h4 class="">Log In</h4>
                            <p class="">Enter your credentials</p>
                            <div class="form-group">
                                <input class="form-control form-control-lg" name="email" type="email" id="email"
                                       placeholder="Enter email" data-toggle="popover" data-placement="top"
                                       data-content="" data-trigger="focus">
                                <p id="mailAlert" class="form-text "></p>
                            </div>
                            <div class="form-group">
                                <input class="form-control form-control-lg" name="pass" type="password" id="password"
                                       placeholder="Password" required data-toggle="popover" data-placement="top"
                                       data-content="" data-trigger="focus">
                                <p id="passAlert" class="form-text "></p>
                            </div>
                            <a href="#" data-toggle="modal" data-target="#register" style="color: white" >
                                Register now!</a>
                            <br>
                            <button class="btn btn-outline-light btn-block" id="submitBtn"
                                    onclick="loginValidation()">Log In</button>
                            <div id="err_login"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- WHAT IS FINANCE TRACKER SECTION -->
<section id="explore-head-section">
    <div class="container">
        <div class="row">
            <div class="col text-center py-5">
                <h1 class="display-4">What can you do with Finance Tracker?</h1>
            </div>
        </div>
    </div>
</section>
<!-- GET THE BIG PICTURE -->
<section id="home-icons" class="py-5 ">
    <div class="container">
        <div class="row">
            <div class="col-md-4 mb-4 text-center">
                <i class="fas fa-cog fa-3x mb-2"></i>
                <h3>Get the big picture</h3>
                <p>Bring all your accounts to one place. See your spending in real-time.</p>
            </div>
            <div class="col-md-4 mb-4 text-center">
                <i class="fas fa-cloud fa-3x mb-2"></i>
                <h3>Know how you spend?</h3>
                <p>Spot spending habits. Learn to spend on things you really want.</p>
            </div>
            <div class="col-md-4 mb-4 text-center">
                <i class="fas fa-cart-plus fa-3x mb-2"></i>
                <h3>Save to achieve goals</h3>
                <p>Create budgets that work for you. Fund your dreams by saving right.</p>
            </div>
        </div>
    </div>
</section>

<!-- REGISTER NOW SECTION -->
<section id="create-head-section" class="bg-primary">
    <div class="container">
        <div class="row">
            <div class="col text-center py-5">
                <h1 class="display-4">Start Now</h1>
                <p class="lead">Assign emotions to your expenses, learn about your real priorities
                    and spend money on things that make you happy!</p>
                <a href="#register" class="btn btn-outline-light" data-toggle="modal" data-target="#register">
                    Register Now</a>
            </div>
        </div>
    </div>
</section>

<!-- EXPLORE SECTION -->
<section id="contact-section" class="bg-light text-muted py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-6 align-self-center">
                <h3>Explore New Opportunities</h3>
                <p>This is a game changer web-service. Check it now!</p>
                <a href="" class="btn btn-outline-primary">Check It</a>
            </div>
            <div class="col-md-6">
                <img src="view/uploads/laptop.png" alt="" class="img-fluid">
            </div>
        </div>
    </div>
</section>

<!-- FOOTER BODY -->
<footer id="main-footer" class="bg-dark">
    <div class="container">
        <div class="row">
            <div class="col text-center py-4">
                <h3>Finance Tracker</h3>
                <p>Copyright &copy; Ivan & Bobby - IT Talents Academy <span id="year"></span></p>
                <button class="btn btn-primary" data-toggle="modal" data-target="#contactModal">Contact us</button>
            </div>
        </div>
    </div>
</footer>

<!-- FOOTER MODAL -->
<div class="modal fade text-dark" id="contactModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Contact us</h5>
                <button class="close" data-dismiss="modal"><span>&times;</span></button>
            </div>
            <div class="modal-body">
                <form class="" action="index.html" method="post">
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" name="" value="" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" name="" value="" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="email">Message</label>
                        <textarea type="email" name="" value="" class="form-control"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary btn-block">Submit</button>
            </div>
        </div>
    </div>
</div>
<!-- MODAL window  Registration-->
<div class="modal fade text-dark" id="register">
        <div class="modal-dialog">
            <div class="modal-content">
                <form action="https://ivan-avramov-finance-tracker.upnetix.tech/users/register" method="post" enctype="multipart/form-data"
                      role="form" onsubmit="return registerValidation(this);">
                    <div class="col-md-12" style="margin: 50px auto">
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title" style="display: inline-block">Register Now</h3>
                                <button class="close" data-dismiss="modal"><span>&times;</span></button>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="first_name">First Name</label>
                                    <input type="text" class="form-control" name="first_name" id="first_name"
                                           placeholder="First Name" >
                                    <div id="firstNameErr"></div>
                                </div>
                                <div class="form-group">
                                    <label for="last_name">Last Name</label>
                                    <input type="text" class="form-control" name="last_name" id="last_name"
                                           placeholder="Last Name" >
                                    <div id="lastNameErr"></div>
                                </div>
                                <div class="form-group">
                                    <label for="email">Email address</label>
                                    <input type="email" class="form-control" name="email" id="reg_email"
                                           placeholder="Enter email" >
                                    <div id="emailErr"></div>
                                </div>
                                <div class="form-group">
                                    <label for="age">Your Age</label>
                                    <input type="text" class="form-control" name="age" id="age"
                                           placeholder="Your Age" >
                                    <div id="ageErr"></div>
                                </div>
                                <div class="form-group">
                                    <label for="password_1">Password</label>
                                    <input type="password" class="form-control" id="password_1" name="password_1"
                                           placeholder="Password" >
                                    <div id="passErr"></div>
                                </div>
                                <div class="form-group">
                                    <label for="password_2">Retype Password</label>
                                    <input type="password" class="form-control" id="password_2" name="password_2"
                                           placeholder="Retype Password" >
                                    <div id="rePassErr"></div>
                                </div>
                                <div class="form-group">
                                    <label for="user_image">File input</label>
                                    <div class="input-group">
                                        <div class="custom-file">
                                            <input type="file" name="user_image" id="user_image">
                                            <div id="imageErr"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <input type="submit" class="btn btn-primary btn-block" name="register" value="Register">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
</div>
<?php require_once "js.php"?>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>
<script src="view/js/validations.js"></script>

<script>
    // Get the current year for the copyright
    $('#year').text(new Date().getFullYear());

    //spy init
    $('body').scrollspy({target:'#main-nav'});

    //smooth scrolling
    $("#main-nav a").on('click',function (event){
        if (this.hash !== "") {
            event.preventDefault();
            const hash = this.hash;

            $('html, body').animate({
                scrollTop: $(hash).offset().top
            }, 800, function(){
                window.location.hash = hash;
            });
        }
    });
</script>
<script src="view/js/handleErrors.js"></script>
</body>
</html>