---
project_url: "{{ project_name }}..upnetix.cloud"

app_env: live

ssl_domain: upnetix.cloud

remote_user: ubuntu

web_host: "{{ hostvars['web_server'].ansible_host }}"

session_host: localhost # "{{ hostvars['web_server'].ansible_host }}"
session_listen_ip: 127.0.0.1 # "{{ hostvars['web_server'].ansible_host }}"

db_host: localhost # "{{ hostvars['db_server'].ansible_host }}"
db_user_host: "%" # localhost  | "{{ hostvars['web_server'].ansible_host }}" - from where can db user connect to

setup_cronjobs: true